# Generated by Django 4.1.5 on 2023-03-04 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0008_alter_invoice_total_amount_alter_lineitem_amount_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoice',
            old_name='customer',
            new_name='student_name',
        ),
        migrations.RenameField(
            model_name='lineitem',
            old_name='customer',
            new_name='student_name',
        ),
    ]
