# Generated by Django 4.1.5 on 2023-03-04 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0009_rename_customer_invoice_student_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoice',
            old_name='customer_email',
            new_name='student_email',
        ),
    ]
