# Generated by Django 4.1.5 on 2023-03-04 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0010_rename_customer_email_invoice_student_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='Level',
            field=models.CharField(blank=True, choices=[('basic', 'Basic'), ('intermediate', 'Intermediate'), ('advance', 'Advance')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='category',
            field=models.CharField(blank=True, choices=[('dance', 'Dance'), ('zumba', 'Zumba'), ('music', 'Music')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='mobile',
            field=models.TextField(blank=True, max_length=12),
        ),
    ]
