# Generated by Django 4.1.5 on 2023-03-04 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0011_invoice_level_invoice_category_invoice_mobile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='Level',
        ),
        migrations.AddField(
            model_name='invoice',
            name='level',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
